services:
  app_umg:
    image: 'umg:latest'
    build:
      context: ./backend  # Updated to point to the backend folder
    container_name: app_umg
    depends_on:
      - db_umg
    env_file:
      - .env
    ports:
      - "8081:8081"
          
  db_umg:
    image: 'postgres:latest'
    container_name: db_umg
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      # Mounts the 'postgres_data' named volume to the container's data directory
      - postgres_data:/var/lib/postgresql/

volumes:
  # Declares the named volume
  postgres_data: