name: cd pipeline

# cd workflow triggered only on release creation
on:
  release:
    types: published

permissions:
  contents: read
  packages: write

jobs:
  release-backend:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
      SPRING_PROFILES_ACTIVE: prod    #sets the active spring profile to prod for the release build
    steps:
      # step 1: checkout repo at release tag
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ env.VERSION }}  # checkout the code at the release tag that triggered this workflow
          fetch-depth: 1           # only fetch this commit

      # step 2: login to ghcr
      - name: Login to github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # step 3: login to docker hub
      # Can either push to public docker hub or will need to do the below. Not sure what marker wants
      # TODO: need to create a docker account for the project and store credentials as secrets in github
      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # step 4: build and push images to GHCR and Docker Hub
      # Release tag for the version that is published becomes the docker image tag
      - name: Build and push images to GHCR and docker hub
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/springboot-backend:${{ env.VERSION }}
            ghcr.io/${{ github.repository_owner }}/springboot-backend:latest
            ${{ secrets.DOCKERHUB_USER }}/springboot-backend:${{ env.VERSION }}
            ${{ secrets.DOCKERHUB_USER }}/springboot-backend:latest
