name: CI pipeline

on:
  push:
    # run tests on all branches
    branches:
      - '**'
  pull_request:
    # run tests on prs to main
    branches: main
  workflow_dispatch:

jobs:
  test-backend:
    runs-on: ubuntu-latest
    # github runner variables
    env:
      DB_HOST: localhost
      DB_USER: myuser
      DB_PASS: secret
      DB_NAME: mydatabase
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: mydatabase
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U myuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # step 1: checkout repository
      - name: Checkout repository
        uses: actions/checkout@v6 

      # step 2: set up java 21 and cache gradle
      - name: Set up Java 21 and cache Gradle
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
          cache-dependency-path: backend/build.gradle

      # step 3: make gradle wrapper executable
      - name: Make Gradle wrapper executable
        run: chmod +x backend/gradlew

      # step 4: wait for postgres
      # we need postgres running for integration tests
      - name: Wait for Postgres to be ready
        run: |
          until pg_isready -h $DB_HOST -p 5432 -U $DB_USER; do
            echo "waiting for postgres..."
            sleep 2
          done

      # step 5: run backend tests
      - name: Run backend tests
        working-directory: backend
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/${{ env.DB_NAME }}
          SPRING_DATASOURCE_USERNAME: ${{ env.DB_USER }}
          SPRING_DATASOURCE_PASSWORD: ${{ env.DB_PASS }}
        run: ./gradlew test --no-daemon

      # optional: SonarCloud analysis
      # use this suggestions on code in PRs. Otherwise we can remove this comment
      # - name: Run SonarCloud scan
      #   uses: SonarSource/sonarcloud-github-action@master
      #   with:
      #     projectKey: your_project_key
      #     organization: your_organization
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
